export const COMMANDS_IN_RUSSIAN = [
  {
    commandIdentifier: "about",
    title: "Обо мне",
    type: "Available records",
    lines: [
      "- Султан Мустафин Женисович",
      "- Дата рождения: 18/11/2002",
      "- Место рождения: Тараз, Южный Казахстан",
      "- Стартап энтузиаст",
      "- Веб разработчик",
    ],
    projects: [],
    lists: [],
    imageName: "glitched-about.gif",
    links: [],
    hints: ["Впишите ‘work’ чтобы открыть опыт работы"],
    error: "",
  },
  {
    commandIdentifier: "work",
    title: "Опыт работы",
    type: "web-developer",
    lines: [
      "- Опыт работы веб-разработчиком начиная с Января 2019 года",
      "- Специализируюсь на создании веб-платформ для активного взаимодействия с пользователями. Активно задействован и заинтересован в участии в независимых проектах и стартапах. Имею актуальный опыт в Ed-tech и E-commerce сферах.",
    ],
    projects: [],
    lists: [
      {
        title: "- Навыки",
        items: [
          "JavaScript",
          "TypeScript",
          "Vue js",
          "Nuxt js",
          "Node js",
          "Nest js",
          "Docker",
          "Express js",
          "HTML",
          "CSS",
        ],
      },
    ],
    imageName: "",
    links: [],
    hints: ["Впишите ‘projects’ чтобы увидеть список проектов"],
    error: "",
  },
  {
    commandIdentifier: "commands",
    title: "Доступные команды",
    type: "available-commands",
    lines: [],
    projects: [],
    lists: [
      {
        title: "",
        items: ["about", "work", "commands", "projects", "contacts", "clear"],
      },
    ],
    imageName: "",
    links: [],
    hints: [],
    error: "",
  },
  {
    commandIdentifier: "projects",
    title: "Проекты",
    type: "projects",
    lines: [],
    projects: [
      {
        linkTitle: "UnApp Space",
        link: "https://unapp.space",
        description:
          "Платформа для подготовки к поступлению в лучшие университеты мира.",
        content:
          "Создал клиентское-приложение с использованием Vue Js, так же разработал RESTful API с использованием Nest Js. Был одним из соучредителей стартапа и принимал активное участие в управленческих и бизнес-решениях команды. Внедрил систему онлайн-эквайринга, перевел backend приложения с Express Js на Nest js.",
      },
      {
        linkTitle: "Sali Market",
        link: "",
        description: "Онлайн платформа для продажи сантехнических товаров.",
        content:
          "Разработал онлайн магазин для продажи сантехники. Спроектировал UI/UX дизайн платформы и архитектуру базы данных. Создал frontend приложение и административную панель на Vue Js, так же разработал RESTful API на Nest Js. Создал гибкую систему категоризации товаров, систему учетов поставок и складирования.",
      },
    ],
    lists: [],
    imageName: "",
    links: [],
    hints: [],
    error: "",
  },
  {
    commandIdentifier: "contacts",
    title: "Связатся со мной",
    type: "contact",
    projects: [],
    lines: [],
    lists: [],
    imageName: "",
    links: [
      {
        title: "Instagram",
        linkTitle: "https://www.instagram.com/itsjustsulya",
        link: "https://www.instagram.com/itsjustsulya",
      },
      {
        title: "LinkedIn",
        linkTitle: "https://www.linkedin.com/in/sultan-mustafin-44382b1a6",
        link: "https://www.linkedin.com/in/sultan-mustafin-44382b1a6",
      },
      {
        title: "Telegram",
        linkTitle: "https://t.me/Sultan_Mus",
        link: "https://t.me/Sultan_Mus",
      },
    ],
    hints: [],
    error: "",
  },
  {
    commandIdentifier: "clear",
    title: "",
    type: "clear",
    lines: [],
    projects: [],
    lists: [],
    imageName: "",
    links: [],
    hints: [],
    error: "",
  },
];
